# Language for the plugin.
# Available: 'en', 'ru', 'es', 'fr', 'zh', 'pt',
# 'de', 'ja', 'ko', 'it', 'hi, 'ar', 'kg', 'pl',
# 'nl', 'sv', 'cs' 'th', 'fi', 'no'
language: 'en'

# Database configuration (MariaDB only) false - yaml storage
database:
  enabled: false
  host: "localhost"
  port: 3306
  name: "minecraft"
  user: "root"
  password: ""

# Leveling system configuration
leveling:
  base_xp: 100
  xp_increment: 50

# Horse stats configuration
stats:
  speed_base: 0.18
  speed_max_bonus: 0.225
  health_base: 15.0
  health_max_bonus: 15.0
  jump_base: 0.6
  jump_max_bonus: 0.6

allow_fall_damage: false
allow_other_players_damage_horses: false

# Horse backpack configuration
# IMPORTANT. Size must be between 9 and 54, and must be a multiple of 9
backpack:
  base_size: 9
  size_per_level: 9
  max_size: 54
  armor_slot_enabled: true
  drop_on_death: true # Drop backpack contents on horse death

# Cooldown in minutes before a dead horse can be respawned
respawn_cooldown_minutes: 15